[package]
name = "tetr-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
screenshots = "0.8.6"
winapi = {version = "0.3", features = ["winuser", "libloaderapi", "processthreadsapi", "tlhelp32"]}
minifb = "0.25"
